Default: &defaults
  user: pbrisbin
  password: password
  host: localhost
  port: 5432

Development:
  <<: *defaults
  database: pbrisbin_dev
  poolsize: 10

Production:
  <<: *defaults
  database: pbrisbin
  poolsize: 100
